// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Contexts;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(OctopusContext))]
    partial class OctopusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("api.Models.Account", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Active = true,
                            CreatedOn = new DateTime(2022, 10, 19, 17, 30, 25, 589, DateTimeKind.Local).AddTicks(2467),
                            Email = "admin@email.com",
                            Password = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Active = true,
                            CreatedOn = new DateTime(2022, 10, 19, 17, 30, 25, 589, DateTimeKind.Local).AddTicks(2503),
                            Email = "user1@email.com",
                            Password = "user1",
                            Username = "user1"
                        },
                        new
                        {
                            UserId = 3,
                            Active = false,
                            CreatedOn = new DateTime(2022, 10, 19, 17, 30, 25, 589, DateTimeKind.Local).AddTicks(2505),
                            Email = "user1@email.com",
                            Password = "user2",
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("api.Models.ApiCall", b =>
                {
                    b.Property<int>("ApiCallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApiCallId"), 1L, 1);

                    b.Property<DateTime>("CalledOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApiCallId");

                    b.ToTable("ApiCalls");
                });

            modelBuilder.Entity("api.Models.ApiKey", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("ApiKeys");

                    b.HasData(
                        new
                        {
                            Key = "1",
                            CreatedOn = new DateTime(2022, 10, 19, 17, 30, 25, 589, DateTimeKind.Local).AddTicks(2604),
                            UserId = 1
                        },
                        new
                        {
                            Key = "mCQ6qIqkNy",
                            CreatedOn = new DateTime(2022, 10, 19, 17, 30, 25, 589, DateTimeKind.Local).AddTicks(2607),
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
